"""
Unit 5 Walk through 
Databases 

Creating databases tables

Django has a default Object Relational Mapper(ORM) built in. The 
ORM allows the use of different databases. For example you might use SQLite for development
and PostgreSQL for production. The ORM handles the differences allowing the code to remain
the same.

We can represent our databases using classes with the Django ORM. 

# 
# 

1. Inside the the blog app directory we have a file called models.py.

├── blog
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-311.pyc
│   │   ├── admin.cpython-311.pyc
│   │   ├── apps.cpython-311.pyc
│   │   ├── models.cpython-311.pyc
│   │   ├── urls.cpython-311.pyc
│   │   └── views.cpython-311.pyc
│   ├── admin.py
│   ├── apps.py
│   ├── migrations
│   │   ├── __init__.py
│   │   └── __pycache__
│   │       └── __init__.cpython-311.pyc
│   ├── models.py
│   ├── static
│   │   └── blog
│   │       └── main.css
│   ├── templates
│   │   └── blog
│   │       ├── about.html
│   │       ├── base.html
│   │       └── home.html
│   ├── tests.py
│   ├── urls.py
│   └── views.py

#
#

2. Open models.py You will see the following
"""
from django.db import models

# Create your models here.

"""

#
#

3. We need to think about what models we want e.g users, post eyc.
Create class named Post with the following attributes.
title, content, date_posted.

models.py should naow have the following code.
"""
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

"""
-> title = models.CharField(max_length=100) --> This sets a title attribute of the character type with a max length of 100.
-> content = models.TextField() --> Sets a content attribute to the TextField type.
-> from django.utils import timezone --> Imports timezone from django.utils
-> date_posted = models.DateTimeField(default=timezone.now) --> Sets date_posted attribute to the current default timezone

Another option for date_posted would be to set date_posted = models.DateTimeField(auto_now_add = True)
This will work when the object is created but does not allow the date to be changed after creation. 

The models.DateTimeField(default=timezone.now) does allow this.

#
#

4. Add an author attribute to the Post class. This is for the User that creates each post.
The User is a separate table so we need to import the User. At the top of models.py add the import
"""
from django.contrib.auth.models import User 

"""
The User to Post relationship will be 1 to Many as 1 User can have multiple posts. In Django we can
specify the 1 to M with a foreign key relationship.

#
#

5. Add 1 to M relationship and set that if a user is deleted all their posts are also removed.
"""
author = models.ForeignKey(User, on_delete=models.CASCADE)
"""
#
#

6. models.py should now have the following code.
"""
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

"""

#
#

7. Update the changes using makemigrations. From the command line run

python manage.py makemigrations

	Output...

	Migrations for 'blog':
	  blog/migrations/0001_initial.py
	    - Create model Post

#
#

8. To see the changes open 0001_initial.py.

├── blog
│   ├── __init__.  
│   ├── admin.py
│   ├── apps.py
│   ├── migrations
│   │   ├── 0001_initial.py
│   │   ├── __init__.py

Do not change the code directly from here. You will see something similar to the following code.

	# Generated by Django 4.2.3 on 2023-07-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]

#
#

9. To view the SQL that will be created from the class Post in models.py use the following command

python manage.py sqlmigrate blog 0001

This can be great if you need to see the exact SQL that is used. The SQL should look similar to the code below.

BEGIN;
--
-- Create model Post
--
CREATE TABLE "blog_post" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, 
                            "title" varchar(100) NOT NULL, 
                            "content" text NOT NULL, 
                            "date_posted" datetime NOT NULL, 
                            "author_id" integer NOT NULL REFERENCES "auth_user" ("id") 
                                    DEFERRABLE INITIALLY DEFERRED);
                                    
CREATE INDEX "blog_post_author_id_dd7a8485" ON "blog_post" ("author_id");
COMMIT;
Django has created this from the class giving the developer an abstraction from having 
to deal with the database directly. This can save time in development.

#
#


[Rob]
9.1 
# [If possible: open/connect/refresh the db.sqlite3 (e.g. SQLiteStudio)
#               and see NO DB tables (blog_post etc) created yet.]



10. Migrate the changes from the command line with the following command

python manage.py migrate

	Output...

    Operations to perform:
    Apply all migrations: admin, auth, blog, contenttypes, sessions
    Running migrations:
    Applying blog.0001_initial... OK


Note: Migrations are very useful because we can make changes to the Database without having to 
work directly with the SQL

#
#

11. Interact with the database via a python shell. Run the following command from the CLI.

python manage.py shell

#
#

12. Inside the shell import the classes. 

>>> from blog.models import Post
>>> from django.contrib.auth.models import User

#
#

13. We have created two Users and we can view them with the following command.

>>> User.objects.all()
<QuerySet [<User: admin>, <User: test>]>
#
#

14. To see the first user created.

>>> User.objects.first()
<User: admin>
#
#

15. filter(). Can be used to filter the Queryset. Example below.

>>> User.objects.filter(username='test')
<QuerySet [<User: test>]>

#
#

16. Storing a filter() inside a variable.

[Rob]
>>> user
<QuerySet [<User: test>]>

# [Note]: the return from filter() is a QuerySet
# [Must: access an individual object to access it's parts]
# [AS such: the following fails...]
#
>>> user.id
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'QuerySet' object has no attribute 'id'



# WHEREAS... calling first() 
#               ...after the filter()
#
>>> user = User.objects.filter(username='test').first()
>>> user.id
2

#
#

17. Use the variable to access attributes. user.id and user.pk. pk (Primary Key)

>>> user
<User: test>
>>> user.id
2
>>> user.pk
2

#
#

18. get(). Below we are using get() to create a user varaibale based on the id=1

>>> user = User.objects.get(id=1)
>>> user
<User: admin>

#
#

19. Check Posts. Posts will be currently empty.

>>> Post.objects.all()
<QuerySet []>

#
#

20. Create a post for <User: admin>

>>> post1 = Post(title="Test BlogPost 21", content="Test post 1 content", author=user)
>>> post1
<Post: Post: Test BlogPost 1>

#
#

21. Run Post.objects.all(). 

>>> Post.objects.all()
<QuerySet []>

# You will see the query set is **still** empty 
# as it's not yet saved to the database.

# [If SQLiteStudio: see DB not blog_post record yet 
#   View with:
#              SELECT * FROM blog_post;

22.Save the post and run Post.objects.all() to see the Post in the query set.

>>> post1.save()
>>> Post.objects.all()
<QuerySet [<Post: Post object (1)>]>
>>>


#
#

23. Create a __str__ in models.py to allow for a more desrciptive info on the object
Open Blog -> models.py and add the code below to the Post model.
"""
def __str__(self):
    return f"{self.__class__.__name__}: {self.title}"

"""

models.py should now have the following code.

	from django.db import models
	from django.utils import timezone
	from django.contrib.auth.models import User

	# Create your models here.
	class Post(models.Model): 
	    title = models.CharField(max_length=100)
	    content = models.TextField()
	    date_posted = models.DateTimeField(default=timezone.now)
	    author = models.ForeignKey(User, on_delete=models.CASCADE)

        def __str__(self):
            return f"{self.__class__.__name__}: {self.title}"

#
#

[Rob]
24.  exit() the shell 
>>> exit()

# 24.1 launch it again...

python manage.py shell


# import Post again

>>> from blog.models import Post

25. Run Post.objects.all() and now we see the blog title 

>>> from blog.models import Post
>>> Post.objects.all()
<QuerySet [<Post: Post: Test BlogPost 1>]>

#
#

26. Access a user again 
#      We have to do this again as python shell variables
#       and imports no longer exist when we exit() the shell

>>> from django.contrib.auth.models import User
>>> user = User.objects.filter(username='test').first()
>>> user
<User: test>

#
#

27. Create another blog post. 

>>> post2 = Post(title="Test BlogPost 2", content="Test post 2 content", author=user)
>>> post2
<Post: Post: Test BlogPost 2>
>>>
#
#

28. Save the blog post 

>>> post2.save()
>>> Post.objects.all()
<QuerySet [<Post: Post: Test BlogPost 1>, <Post: Post: Test BlogPost 2>]>

[Rob]
# Recall    'save()'        creates a Post record in the DB
#           'Post.objects'  accesses the Posts table in theDB
#



29. Save Post.objects.first() in a variable called post.

>>> post = Post.objects.first()
>>> post
<Post: Post: Test BlogPost 1>



#
#

30. Access the attributes of the post object

>>> post.content
'Test post 1 content'

>>> post.author
<User: admin>

>>> post.date_posted
datetime.datetime(2026, 4, 13, 15, 31, 56, 26490, tzinfo=datetime.timezone.utc)


#
#

[Rob]
31. 'post' is a Python object. It allows us to use Python
    to access the 'Post' DB table. It also allows us to 
    use Python to access related DB tables like the 
    User table we have a foreign-key to Post.author.

>>> post.author.email
'test@test.com'

>>> post.author.password
'pbkdf2_sha256$1200000$2aWlcavOHVwNlz1VUGeD2i$Y9rCt9Q4HK19KCzFB2utlkNyeeVtKR5kQ/qrV5StI3E='


#[Rob]
#   Access the DB (e.g. db.sqlite3, using SQLiteStudio) and  
#   view the auth_user table (SELECT * FROM auth_user;).
#   Experiment with other attributes of the 'author' (DB 'User')
#   table you can access...



32.  Access a User in Python and use it to lookup the Posts that user has made
        again, with Python (this is all achieved through the Django ORM API).

>>>> user = User.objects.get(id=1)
>>> user
<User: admin>
>>> user.post_set
<django.db.models.fields.related_descriptors.create_reverse_many_to_one_manager.<locals>.RelatedManager object at 0x00000221C106E3C0>
>>>


[Rob]
# See 
# https://docs.djangoproject.com/en/6.0/intro/tutorial02/#playing-with-the-api
#
# "Django creates  a set..." in this case "post_set" that holds "...the "other side" 
# of a ForeignKey relation" (e.g. a user's posts) "...which can be accessed via the API." 


The output above is not very useful as it stands below...

<django.db.models.fields.related_descriptors.create_reverse_many_to_one_manager.<locals>.RelatedManager object at 0x1031dfe10>

... however
#
#

33. Run user.post_set.all()

>>> user.post_set.all()
<QuerySet [<Post: Post: Test BlogPost 1>]>

allows us to access, in this case, the 'admin' user's posts as Python objects.

#
#

[Rob]
34. Create a new blog post with post_set.create()

>>> user.post_set.create(title="Test BlogPost 3", content="Test post 3 content")                  
<Post: Post: Test BlogPost 3>
>>> user.post_set.all()
<QuerySet [<Post: Post: Test BlogPost 1>, <Post: Post: Test BlogPost 3>]>


# Note: create() automatically saves this new Post in the DB (view the DB to see).

>>> Post.objects.all()
<QuerySet [<Post: Post: Test BlogPost 1>, <Post: Post: Test BlogPost 2>, <Post: Post: Test BlogPost 3>]>

# Note: the 'author' for the Post is automatically the 'user' from 'user.post_set.create(...)'

#
#


[Rob]
##
exit() the shell

>>> exit()

36. Open Blog -> views.py
Inside views.py import the Post class
"""
from .models import Post

"""

#
#

37. Update the home view

from ...

def home(request):
    context = {
        'posts': posts
    }
    return render(request, 'blog/home.html', context)

to ...
"""

def home(request):
    context = {
       'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)
"""

#
#

38. Run the development server and now you will see three blog posts 
and the date formatting from the database.

python manage.py runserver

#
#

39. Currently the the date created is showing the timestamp. 
This can be useful for certain applications but for now we will
change the format using Django Date Formatting.

Refer to https://docs.djangoproject.com/en/6.0/ref/templates/builtins/#date

#
#

40. Open Blog -> templates -> blog -> home.html

Update {{ post.date_posted }}

from ...

<small class="text-muted">{{ post.date_posted }}</small>

to ...

{{ post.date_posted|date:'dS, F, Y' }}

Template tags can have a filter:
https://docs.djangoproject.com/en/6.0/ref/templates/builtins/#built-in-filter-reference

Above we are using the date filter and specifying the
format in a string as 
    d = Day of the month, 2 digits with leading zeros. '01' to '31', 
    S = suffix [1st ('st'), 2'nd'(2nd), 'rd' or 'th' etc.],
    F = Month, textual, long. 'January', 
    Y = Year, 4 digits '1999',...'2025' etc.

# 
#

41. Delete the dummy data from the blog -> views.py

The dummy data was...

posts = [
    {
        "author": "Bill Tutman",
        "title": "Getting Started with Django",
        "content": "A django basics and understandings post.",
        "date_posted": "05/02/2026"
    },

    {
        "author": "Djan Gu",
        "title": "Don't forget the django tutorial",
        "content": "Exploring frameworks like django post.",
        "date_posted": "18/03/2026"
    }
]

views.py when updated should now look like the following
"""

from django.shortcuts import render
from django.http import HttpResponse
from .models import Post

# Create your views here.x
def home(request):
    context = {
       'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

"""

#
#
[Rob]

42. We can use the /admin GUI (Django Admin page) to create/read/update/delete Posts
    in the DB. To this we need to first register the Post Model with 
    the admin page using admin.site.register().
Before doing this open up the admin page http://127.0.0.1:8000/admin/

Under AUTHENTICATION AND AUTHORIZATION you will see

Groups
Users

#
#

[Rob]
43. Open blog -> admin.py

Inside admin.py: register the model to the admin page as follows.
"""

from django.contrib import admin
from .models import Post                    #ADD

admin.site.register(Post)                   #ADD
"""

Save the file and reload the browser's /admin page. You will now see
a section for:

-------
Posts 
-------

has appeared.

Go into Posts and you will see:
    Post: Test BlogPost 3
	Post: Test BlogPost 2
	Post: Test BlogPost 1

(or whatever Titles you gave your posts earlier.)



44.
Use the Django Admin GUI to add a new post, to update an existing post 
and to delete a post. Examine the DB each time and see the effect 
persists to the DB.

# [Note: for 'delete': tick the checkbox and select
#        'Delete selected posts' from the 'Action' drop-down
#         above the list and click the 'Run' button].



This Django Admin GUI (/admin) is a very powerful feature of Django
giving back-end functionality without having to build your own GUI.

It's particularly useful to test your models, users & permissions 
during development.

We have used it to demonstrate Create, Read, Update & Delete (CRUD)
operations.

"""
























